apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: staging
data:
  application-prod.yml: |
    spring:
      cloud:
        gateway:
          routes:
          - id: ORDER-SERVICE
            uri: http://order-service:8300
            predicates:
            - Path=/order-service/**
          - id: PAYMENT-SERVICE
            uri: http://payment-service:8400
            predicates:
            - Path=/payment-service/**
          - id: PRODUCT-SERVICE
            uri: http://product-service:8500
            predicates:
            - Path=/product-service/**
          - id: SHIPPING-SERVICE
            uri: http://shipping-service:8600
            predicates:
            - Path=/shipping-service/**
          - id: USER-SERVICE
            uri: http://user-service:8700
            predicates:
            - Path=/user-service/**
          - id: FAVOURITE-SERVICE
            uri: http://favourite-service:8800
            predicates:
            - Path=/favourite-service/**
          - id: PROXY-CLIENT
            uri: http://proxy-client:8090
            predicates:
            - Path=/app/**
