apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  namespace: staging
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /user-service
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 8700
      - path: /product-service
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 8500
      - path: /order-service
        pathType: Prefix
        backend:
          service:
            name: order-service
            port:
              number: 8300
      - path: /payment-service
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port:
              number: 8400
      - path: /shipping-service
        pathType: Prefix
        backend:
          service:
            name: shipping-service
            port:
              number: 8600
      - path: /favourite-service
        pathType: Prefix
        backend:
          service:
            name: favourite-service
            port:
              number: 8800
