fullnameOverride: proxy-client

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/rock-fortress-479417-t5/ecommerce-microservices/proxy-client
  tag: dev
  pullPolicy: Always

service:
  type: NodePort
  port: 80
  targetPort: 8080
  nodePort: 30900

readinessProbe:
  path: /app/actuator/health
  port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe:
  path: /app/actuator/health
  port: 8080
  initialDelaySeconds: 90
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 3

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "staging"
  - name: SPRING_ZIPKIN_BASE_URL
    value: "http://zipkin:9411/"
  - name: eureka.client.service-url.defaultZone
    value: "http://discovery:8761/eureka"
  - name: EUREKA_INSTANCE_HOSTNAME
    value: "proxy-client"
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "true"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "true"
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "true"
  - name: EUREKA_CLIENT_ENABLED
    value: "true"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info,metrics"

ingress:
  enabled: false
