env:
  - name: SPRING_PROFILES_ACTIVE
    value: "staging"
  - name: SPRING_ZIPKIN_BASE_URL
    value: "http://zipkin:9411/"
  - name: eureka.client.service-url.defaultZone
    value: "http://discovery:8761/eureka"
  - name: EUREKA_INSTANCE_HOSTNAME
    value: "proxy-client"
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "false"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "false"
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"
  - name: EUREKA_CLIENT_ENABLED
    value: "false"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info,metrics"
