fullnameOverride: cloud-config

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/rock-fortress-479417-t5/ecommerce-microservices/cloud-config
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 9296

serviceAccount:
  create: false

ingress:
  enabled: false

httpRoute:
  enabled: false

autoscaling:
  enabled: false

resources: {}

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "native"
  - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
    value: "http://discovery:8761/eureka/"
  - name: SPRING_ZIPKIN_BASE_URL
    value: "http://zipkin:9411/"
