# manifests-gcp/shipping-service/values.yaml
fullnameOverride: shipping-service

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/rock-fortress-479417-t5/ecommerce-microservices/shipping-service
  tag: latest-dev
  pullPolicy: Always

service:
  type: NodePort
  port: 8600
  targetPort: 8600

readinessProbe:
  path: /shipping-service/actuator/health
  port: 8600
  initialDelaySeconds: 120
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

livenessProbe:
  path: /shipping-service/actuator/health
  port: 8600
  initialDelaySeconds: 150
  periodSeconds: 15
  timeoutSeconds: 5
  failureThreshold: 4

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "stage"
  - name: SPRING_CONFIG_IMPORT
    value: "optional:configserver:http://cloud-config:9296"
  - name: SPRING_ZIPKIN_BASE_URL
    value: "http://zipkin:9411/"
  - name: eureka.client.service-url.defaultZone
    value: "http://discovery:8761/eureka"
  - name: EUREKA_INSTANCE_HOSTNAME
    value: "shipping-service"
  - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
    value: "false"
  - name: EUREKA_CLIENT_FETCH_REGISTRY
    value: "false"
  - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
    value: "false"
  - name: EUREKA_CLIENT_ENABLED
    value: "false"
  - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
    value: "health,info,metrics"
  - name: SPRING_DATASOURCE_URL
    value: "jdbc:mysql://mysql:3306/ecommerce_shipping_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false"
  - name: SPRING_DATASOURCE_USERNAME
    value: "root"
  - name: SPRING_DATASOURCE_PASSWORD
    value: ""
ingress:
  enabled: false
  className: "gce"
  annotations:
    kubernetes.io/ingress.class: "gce"
  hosts:
    - host: ""
      paths:
        - path: /shipping-service
          pathType: Prefix
  tls: []
